# -*- coding: utf-8 -*-
"""220 yeni tarif paketindeki malzeme adları → kanonik katalog ID(leri).

`ing_map.py`'nin üstüne biner: önce oradaki eşleme, sonra buradaki denenir.
`NEW_INGREDIENTS` katalogda karşılığı olmayan, eklenmesi gereken malzemeler
(besin değerleri 100 g / 100 ml başına).
"""

# id: (tr, en, kategori, alerjenler, (kcal, protein, karb, yağ, lif), porsiyon)
NEW_INGREDIENTS = {
    # ── süt ürünleri ve alternatifleri ────────────────────────────────
    'lactose_free_yogurt': ('Laktozsuz Yoğurt', 'Lactose-Free Turkish Yogurt',
                            'dairy', ['dairy'], (61, 3.5, 4.7, 3.3, 0.0), 150),
    'soy_milk': ('Soya İçeceği', 'Soy Drink', 'beverage', ['soy'],
                 (45, 3.3, 2.7, 1.8, 0.5), 200),
    'halloumi': ('Hellim', 'Halloumi', 'dairy', ['dairy'],
                 (321, 22.0, 2.2, 25.0, 0.0), 50),
    'gruyere': ('Gravyer', 'Gruyère', 'dairy', ['dairy'],
                (413, 30.0, 0.4, 32.0, 0.0), 30),
    'string_cheese': ('Telli Peynir', 'String Cheese', 'dairy', ['dairy'],
                      (300, 24.0, 2.0, 22.0, 0.0), 40),
    'whey_protein': ('Peynir Altı Suyu Proteini', 'Whey Protein Powder',
                     'protein', ['dairy'], (400, 80.0, 8.0, 5.0, 1.0), 30),

    # ── et / balık ────────────────────────────────────────────────────
    'sucuk': ('Sucuk', 'Sucuk', 'protein', [],
              (380, 22.0, 2.0, 32.0, 0.0), 40),
    'pastirma': ('Pastırma', 'Pastirma', 'protein', [],
                 (240, 40.0, 1.0, 8.0, 0.0), 30),
    'sausage': ('Sosis', 'Sausage', 'protein', [],
                (250, 15.0, 2.0, 20.0, 0.0), 60),
    'mackerel': ('Uskumru', 'Mackerel', 'protein', ['fish'],
                 (205, 19.0, 0.0, 13.9, 0.0), 120),
    'trout': ('Alabalık', 'Trout', 'protein', ['fish'],
              (148, 20.8, 0.0, 6.6, 0.0), 120),
    'beef_jerky': ('Kurutulmuş Et', 'Beef Jerky', 'snackFood', [],
                   (410, 33.0, 11.0, 25.0, 1.5), 30),

    # ── tahıl / hamur ─────────────────────────────────────────────────
    'chickpea_flour': ('Nohut Unu', 'Chickpea Flour', 'grain', [],
                       (387, 22.4, 57.8, 6.7, 10.8), 50),
    'lasagna_sheets': ('Lazanya Yaprağı', 'Lasagne Sheets', 'grain',
                       ['gluten'], (352, 12.0, 71.0, 1.5, 3.0), 80),
    'gnocchi': ('Gnocchi', 'Gnocchi', 'grain', ['gluten'],
                (165, 4.0, 33.0, 1.5, 2.0), 200),
    'ravioli': ('Ravioli', 'Ravioli', 'grain', ['gluten', 'eggs', 'dairy'],
                (280, 11.0, 40.0, 8.0, 2.0), 150),
    'croissant': ('Kruvasan', 'Croissant', 'grain', ['gluten', 'dairy'],
                  (406, 8.2, 45.8, 21.0, 2.6), 60),
    'bagel': ('Bagel', 'Bagel', 'grain', ['gluten'],
              (250, 10.0, 48.0, 1.5, 2.1), 90),
    'waffle': ('Waffle', 'Waffle', 'grain', ['gluten', 'eggs', 'dairy'],
               (291, 7.9, 32.9, 14.1, 2.4), 75),
    'pizza_dough': ('Pizza Hamuru', 'Pizza Dough', 'grain', ['gluten'],
                    (265, 8.9, 49.0, 3.2, 2.2), 120),
    'quiche_pastry': ('Tart Hamuru', 'Shortcrust Pastry', 'grain',
                      ['gluten', 'dairy'], (450, 6.0, 45.0, 27.0, 1.8), 80),
    'breakfast_cereal': ('Tam Tahıllı Gevrek', 'Whole-Grain Cereal', 'grain',
                         ['gluten'], (367, 10.0, 72.0, 3.5, 10.0), 40),
    'croutons': ('Kruton', 'Croutons', 'grain', ['gluten'],
                 (407, 11.9, 73.5, 6.6, 5.0), 20),
    'rice_paper': ('Pirinç Kâğıdı', 'Rice Paper Wrappers', 'grain', [],
                   (333, 0.5, 82.0, 0.2, 2.0), 30),
    'wheat_berries': ('Aşurelik Buğday', 'Pearled Wheat', 'grain', ['gluten'],
                      (340, 12.0, 71.0, 1.5, 12.0), 60),

    # ── sebze / meyve ─────────────────────────────────────────────────
    'pak_choi': ('Pak Choi', 'Pak Choi', 'vegetable', [],
                 (13, 1.5, 2.2, 0.2, 1.0), 100),
    'bean_sprouts': ('Fasulye Filizi', 'Bean Sprouts', 'vegetable', [],
                     (30, 3.0, 5.9, 0.2, 1.8), 60),
    'bamboo_shoots': ('Bambu Filizi', 'Bamboo Shoots', 'vegetable', [],
                      (27, 2.6, 5.2, 0.3, 2.2), 60),
    'sugar_snap_peas': ('Şeker Bezelye', 'Sugar Snap Peas', 'vegetable', [],
                        (42, 2.8, 7.6, 0.2, 2.6), 80),
    'sour_cherry': ('Vişne', 'Sour Cherry', 'fruit', [],
                    (50, 1.0, 12.2, 0.3, 1.6), 100),
    'wakame': ('Wakame', 'Wakame', 'vegetable', [],
               (290, 17.0, 45.0, 2.5, 33.0), 5),
    'kimchi': ('Kimchi', 'Kimchi', 'vegetable', [],
               (23, 1.7, 2.4, 0.5, 1.6), 50),
    'capers': ('Kapari', 'Capers', 'condiment', [],
               (23, 2.4, 4.9, 0.9, 3.2), 10),
    'chives': ('Frenk Soğanı', 'Chives', 'spice', [],
               (30, 3.3, 4.4, 0.7, 2.5), 5),
    'radish_sprouts': ('Turp Filizi', 'Radish Sprouts', 'vegetable', [],
                       (43, 3.8, 3.6, 2.5, 1.6), 20),

    # ── sos / baharat / diğer ─────────────────────────────────────────
    'chicken_stock': ('Tavuk Suyu', 'Chicken Stock', 'other', [],
                      (7, 1.0, 0.5, 0.2, 0.0), 250),
    'beef_stock': ('Et Suyu', 'Beef Stock', 'other', [],
                   (8, 1.2, 0.5, 0.2, 0.0), 250),
    'vegetable_stock': ('Sebze Suyu', 'Vegetable Stock', 'other', [],
                        (5, 0.3, 0.9, 0.1, 0.0), 250),
    'fish_stock': ('Balık Suyu', 'Fish Stock', 'other', ['fish'],
                   (8, 1.2, 0.5, 0.2, 0.0), 250),
    'tomato_sauce': ('Domates Sosu', 'Tomato Sauce', 'condiment', [],
                     (32, 1.6, 7.0, 0.2, 1.5), 100),
    'salsa': ('Salsa Sosu', 'Salsa', 'condiment', [],
              (36, 1.5, 7.0, 0.2, 1.8), 50),
    'pesto': ('Pesto', 'Basil Pesto', 'condiment', ['nuts', 'dairy'],
              (450, 5.0, 6.0, 45.0, 2.0), 25),
    'hummus': ('Humus', 'Hummus', 'condiment', ['sesame'],
               (166, 7.9, 14.3, 9.6, 6.0), 60),
    'gochujang': ('Gochujang', 'Gochujang', 'condiment', ['soy', 'gluten'],
                  (214, 5.5, 42.0, 2.0, 3.0), 20),
    'tamari': ('Tamari', 'Tamari', 'condiment', ['soy'],
               (60, 10.5, 5.6, 0.1, 0.8), 15),
    'fish_sauce': ('Balık Sosu', 'Fish Sauce', 'condiment', ['fish'],
                   (35, 5.1, 3.6, 0.0, 0.0), 10),
    'mirin': ('Mirin', 'Mirin', 'condiment', [],
              (258, 0.2, 43.0, 0.0, 0.0), 15),
    'rice_vinegar': ('Pirinç Sirkesi', 'Rice Vinegar', 'condiment', [],
                     (18, 0.3, 0.5, 0.0, 0.0), 15),
    'curry_paste': ('Köri Ezmesi', 'Curry Paste', 'condiment', [],
                    (130, 3.0, 15.0, 6.0, 4.0), 20),
    'peanut_sauce': ('Fıstık Sosu', 'Peanut Sauce', 'condiment', ['peanuts'],
                     (350, 12.0, 20.0, 25.0, 3.0), 30),
    'cranberry_sauce': ('Turna Yemişi Sosu', 'Cranberry Sauce', 'condiment',
                        [], (151, 0.1, 39.0, 0.1, 1.1), 30),
    'enchilada_sauce': ('Enchilada Sosu', 'Enchilada Sauce', 'condiment', [],
                        (60, 1.5, 9.0, 2.0, 2.0), 60),
    'baked_beans': ('Domates Soslu Fasulye', 'Baked Beans', 'legume', [],
                    (94, 4.8, 15.0, 0.5, 4.1), 150),
    'nutritional_yeast': ('Besin Mayası', 'Nutritional Yeast', 'other', [],
                          (385, 50.0, 36.0, 5.0, 21.0), 10),
    'cacao_nibs': ('Kakao Parçacığı', 'Cacao Nibs', 'snackFood', [],
                   (654, 14.0, 46.0, 43.0, 37.0), 15),
    'saffron': ('Safran', 'Saffron', 'spice', [],
                (310, 11.4, 65.0, 5.9, 3.9), 1),
    'garam_masala': ('Garam Masala', 'Garam Masala', 'spice', [],
                     (379, 14.0, 45.0, 15.0, 25.0), 3),
    'cajun_seasoning': ('Cajun Baharatı', 'Cajun Seasoning', 'spice', [],
                        (300, 11.0, 50.0, 8.0, 20.0), 3),
    'star_anise': ('Yıldız Anason', 'Star Anise', 'spice', [],
                   (337, 17.6, 50.0, 15.9, 14.6), 1),
    'sage': ('Adaçayı', 'Sage', 'spice', [],
             (315, 10.6, 60.7, 12.8, 40.3), 2),
}

# Rapordaki TR ad → [katalog id]
MAP = {
    # ── mevcut kataloğa inen nitelemeler ─────────────────────────────
    'Ayıklanmış çiğ karides': ['shrimp'],
    'Çiğ karides': ['shrimp'],
    'Kabuklu temizlenmiş midye': ['mussel'],
    'Somon fileto': ['salmon'],
    'Füme somon': ['salmon'],
    'Levrek fileto': ['sea_bass'],
    'Çipura fileto': ['sea_bream'],
    'Alabalık fileto': ['trout'],
    'Füme alabalık': ['trout'],
    'Uskumru fileto': ['mackerel'],
    'Füme uskumru': ['mackerel'],
    'Beyaz balık fileto': ['cod'],
    'Ançüez filetosu': ['anchovy'],
    'Suda sardalya, süzülmüş': ['sardine'],
    'Suda veya zeytinyağında sardalya, süzülmüş': ['sardine'],
    'Suda ton balığı, süzülmüş': ['tuna'],
    'Hindi füme': ['turkey_breast'],
    'Hindi jambon': ['turkey_breast'],
    'Hindi füme veya pişmiş hindi': ['turkey_breast'],
    'Hindi kıyma': ['ground_turkey'],
    'Kuzu kıyma': ['lamb'],
    'Kuşbaşı kuzu eti': ['lamb'],
    'Dana bonfile': ['beef_steak'],
    'Dana bonfile veya kontrfile': ['beef_steak'],
    'Dana kuşbaşı': ['veal'],
    'Kemiksiz tavuk kalça': ['chicken_thigh'],
    'Çiğ tavuk sosisi': ['sausage'],
    'Tavuk sosis': ['sausage'],
    'Çiğ dana sosis': ['sausage'],
    'Dana kurutulmuş et': ['beef_jerky'],
    'Yumurta akı': ['eggs'],
    'Pastörize yumurta sarısı': ['eggs'],

    # ── süt ürünleri ──────────────────────────────────────────────────
    'Laktozsuz yoğurt': ['lactose_free_yogurt'],
    'Şekersiz soya içeceği': ['soy_milk'],
    'Soya içeceği': ['soy_milk'],
    'Hellim': ['halloumi'],
    'Gravyer peyniri': ['gruyere'],
    'Kolot veya telli peynir': ['string_cheese'],
    'Eski kaşar': ['cheddar_cheese'],
    'Mini mozzarella': ['mozzarella'],
    'Peynir altı suyu protein tozu': ['whey_protein'],
    'Hafif Hindistan cevizi sütü': ['coconut_milk'],

    # ── ekmek / tahıl ─────────────────────────────────────────────────
    'Tam buğday ekmeği': ['bread'],
    'Çavdar ekmeği': ['bread'],
    'Tam tahıllı baget': ['bread'],
    'Tam tahıllı panini ekmeği': ['bread'],
    'Tam tahıllı küçük ekmek': ['bread'],
    'İngiliz muffin veya ekmek': ['bread'],
    'Tam tahıllı bagel': ['bagel'],
    'Sade kruvasan': ['croissant'],
    'Pişmiş tam buğday waffle': ['waffle'],
    'Tam buğday pide': ['pita_bread'],
    'Tam buğday yufka': ['phyllo_dough'],
    'Tam tahıllı lavaş': ['tortilla_wrap'],
    'Tam tahıllı tortilla': ['tortilla_wrap'],
    'Tam buğday tortilla': ['tortilla_wrap'],
    'Küçük buğday tortilla': ['tortilla_wrap'],
    'Mısır tortilla': ['tortilla_wrap'],
    'Tam buğday pizza hamuru': ['pizza_dough'],
    'Hazır kiş hamuru veya tart hamuru': ['quiche_pastry'],
    'Tam tahıllı kraker': ['crackers'],
    'Çavdar galeta': ['crackers'],
    'Tam tahıllı gevrek': ['breakfast_cereal'],
    'Tam tahıllı kruton': ['croutons'],
    'Pirinç kâğıdı': ['rice_paper'],
    'Aşurelik buğday': ['wheat_berries'],
    'Nohut unu': ['chickpea_flour'],
    'Glütensiz etiketli yulaf ezmesi': ['oats'],
    'Yulaf ezmesi': ['oats'],
    'Kuru polenta': ['cornmeal'],
    'Glütensiz etiketli kuru polenta': ['cornmeal'],
    'Lazanya yaprağı': ['lasagna_sheets'],
    'Cannelloni tüpü': ['lasagna_sheets'],
    'Patates gnocchi': ['gnocchi'],
    'Taze balkabaklı ricotta ravioli': ['ravioli'],
    'Glütensiz etiketli sade pirinç patlağı': ['rice_cake'],
    'Sade pirinç patlağı': ['rice_cake'],

    # makarna / erişte / pirinç (kuru bazlı; "Pişmiş" olanlar çevriliyor)
    'Kuru orzo': ['pasta'],
    'Pişmiş arpa şehriye': ['pasta'],
    'Kuru linguine': ['pasta'],
    'Kuru pappardelle': ['pasta'],
    'Pişmiş kısa makarna': ['pasta'],
    'Pişmiş tam buğday makarna': ['pasta'],
    'Pişmiş spagetti': ['pasta'],
    'Pişmiş tam buğday spagetti': ['pasta'],
    'Kuru soba noodle': ['noodle'],
    'Ramen eriştesi': ['noodle'],
    'Kuru yumurtalı erişte': ['noodle'],
    'Pişmiş yumurtalı erişte': ['noodle'],
    'Pişmiş udon noodle': ['noodle'],
    'Pişmiş pirinç noodle': ['noodle'],
    'Pişmiş pirinç eriştesi': ['noodle'],
    'Kuru kısa taneli pirinç': ['white_rice'],
    'Pişmiş yasemin pirinci': ['white_rice'],
    'Pişmiş sushi pirinci': ['white_rice'],

    # ── bakliyat ──────────────────────────────────────────────────────
    'Pişmiş kırmızı fasulye': ['kidney_bean'],
    'Pişmiş beyaz fasulye': ['white_bean'],
    'Pişmiş, süzülmüş beyaz fasulye': ['white_bean'],
    'Domates soslu kuru fasulye': ['baked_beans'],
    'Pişmiş, ayıklanmış edamame': ['edamame'],

    # ── sebze / meyve ─────────────────────────────────────────────────
    'Kiraz domates': ['tomato'],
    'Domates püresi': ['tomato'],
    'Domates sosu': ['tomato_sauce'],
    'Domates salsa': ['salsa'],
    'Domates salsası': ['salsa'],
    'Domates salçası': ['tomato_paste'],
    'Sivri biber': ['bell_pepper'],
    'Közlenmiş kırmızı biber': ['bell_pepper'],
    'Köz biber': ['bell_pepper'],
    'Büyük dolmalık biber': ['bell_pepper'],
    'Mini tatlı biber': ['bell_pepper'],
    'Marul yaprağı': ['lettuce'],
    'Yedikule marulu': ['lettuce'],
    'Mevsim salatası': ['lettuce'],
    'Ispanak yaprağı': ['spinach'],
    'Haşlanmış patates': ['potato'],
    'Beyaz lahana': ['cabbage'],
    'Salatalık turşusu': ['pickles'],
    'Çekirdeksiz zeytin': ['olives'],
    'Çekirdeksiz üzüm': ['grape'],
    'Karışık orman meyveleri': ['blueberry', 'raspberry'],
    'Orman meyveleri': ['blueberry', 'raspberry'],
    'Orman meyvesi': ['blueberry', 'raspberry'],
    'Dondurulmuş orman meyvesi': ['blueberry', 'raspberry'],
    'Çekirdeksiz vişne': ['sour_cherry'],
    'Hurma, çekirdeksiz': ['dates'],
    'File badem': ['almond'],
    'Limon kabuğu rendesi': ['lemon'],
    'Portakal kabuğu rendesi': ['orange'],
    'Turp filizi': ['radish_sprouts'],
    'Fasulye filizi': ['bean_sprouts'],
    'Bambu filizi': ['bamboo_shoots'],
    'Şeker bezelye': ['sugar_snap_peas'],
    'Pak choi': ['pak_choi'],
    'Kuru wakame': ['wakame'],
    'Domates ve salatalık': ['tomato', 'cucumber'],

    # ── sos / baharat ─────────────────────────────────────────────────
    'Et suyu': ['beef_stock'],
    'Tavuk suyu': ['chicken_stock'],
    'Sebze suyu': ['vegetable_stock'],
    'Balık suyu': ['fish_stock'],
    'Tavuk veya sebze suyu': ['chicken_stock'],
    'Fesleğen pestosu': ['pesto'],
    'Humus': ['hummus'],
    'Gochujang': ['gochujang'],
    'Kimchi': ['kimchi'],
    'Glütensiz etiketli tamari': ['tamari'],
    'Balık sosu': ['fish_sauce'],
    'Mirin': ['mirin'],
    'Pirinç sirkesi': ['rice_vinegar'],
    'Sirke': ['white_vinegar'],
    'Kırmızı köri ezmesi': ['curry_paste'],
    'Yeşil köri ezmesi': ['curry_paste'],
    'Fıstık sosu': ['peanut_sauce'],
    'Turna yemişi sosu': ['cranberry_sauce'],
    'Enchilada sosu': ['enchilada_sauce'],
    'Besin mayası': ['nutritional_yeast'],
    'Glütensiz etiketli besin mayası': ['nutritional_yeast'],
    'Kakao parçacığı': ['cacao_nibs'],
    'Kapar': ['capers'],
    'Frenk soğanı': ['chives'],
    'Taze adaçayı': ['sage'],
    'Safran': ['saffron'],
    'Garam masala': ['garam_masala'],
    'Cajun baharatı': ['cajun_seasoning'],
    'Yıldız anason': ['star_anise'],
    'Zencefil': ['ginger'],
    'Tatlı paprika': ['paprika'],
    'Üzüm pekmezi': ['molasses'],
    'Sucuk': ['sucuk'],
    'Pastırma': ['pastirma'],

    # ── birleşik baharat satırları ────────────────────────────────────
    'Tuz, karabiber ve kekik': ['salt', 'black_pepper', 'oregano'],
    'Kekik ve karabiber': ['oregano', 'black_pepper'],
    'Tuz ve kimyon': ['salt', 'cumin'],
    'Kimyon ve toz biber': ['cumin', 'paprika'],
    'Kimyon ve kişniş': ['cumin', 'coriander'],
    'Kimyon ve tarçın': ['cumin', 'cinnamon'],
}

# "Pişmiş X" verilen ama besin tablosunda KURU tutulan malzemeler için
# pişmiş → kuru çevrim katsayıları.
COOKED_TO_DRY_FACTORS = {
    'white_rice': 2.75,
    'pasta': 2.4,
    'noodle': 2.5,
    'couscous': 2.5,
    'quinoa': 3.0,
    'barley': 3.0,
    'bulgur': 2.8,
    'red_lentil': 2.4,
    'green_lentil': 2.4,
    'fava_bean': 2.4,
    'wheat_berries': 2.6,
}
