# -*- coding: utf-8 -*-
"""Rapordaki malzeme adı -> kanonik katalog ID(leri).

Bir satır birden çok malzeme içerebilir ("Tuz ve karabiber"), o yüzden
değerler liste. NEW_* ile işaretlenenler katalogda yok, eklenmesi gerekiyor.
"""

# Katalogda karşılığı olmayan, eklenecek malzemeler
NEW_INGREDIENTS = {
    # id: (tr, en, kategori, alerjenler, per100g kcal/protein/carb/fat/fiber, porsiyon)
    'water': ('Su', 'Water', 'other', [], (0, 0.0, 0.0, 0.0, 0.0), 250),
    'miso_paste': ('Miso', 'Miso Paste', 'condiment', ['soy'],
                   (198, 12.8, 25.4, 6.0, 5.4), 15),
    'grape_leaves': ('Asma Yaprağı', 'Grape Leaves', 'vegetable', [],
                     (69, 5.6, 11.0, 2.1, 11.0), 50),
    'pecorino': ('Pecorino', 'Pecorino Romano', 'dairy', ['dairy'],
                 (387, 32.0, 3.6, 26.9, 0.0), 20),
    'granola': ('Granola', 'Granola', 'grain', ['gluten'],
                (471, 10.0, 64.0, 20.0, 7.0), 40),
    'coconut_water': ('Hindistancevizi Suyu', 'Coconut Water', 'other', [],
                      (19, 0.7, 3.7, 0.2, 1.1), 250),
}

# Rapordaki TR adı -> [katalog id]
MAP = {
    # ── birleşik baharat satırları ────────────────────────────────────
    'Tuz ve karabiber': ['salt', 'black_pepper'],
    'Tuz, karabiber ve pul biber': ['salt', 'black_pepper',
                                    'red_pepper_flakes'],
    'Pul biber, tuz ve karabiber': ['red_pepper_flakes', 'salt',
                                    'black_pepper'],
    'Pul biber ve tuz': ['red_pepper_flakes', 'salt'],
    'Kekik, tuz ve karabiber': ['oregano', 'salt', 'black_pepper'],
    'Kimyon, tuz ve karabiber': ['cumin', 'salt', 'black_pepper'],
    'Toz kırmızı biber, tuz ve karabiber': ['paprika', 'salt', 'black_pepper'],
    'Toz kırmızı biber ve kimyon': ['paprika', 'cumin'],
    'Kimyon ve toz kırmızı biber': ['cumin', 'paprika'],
    'Kimyon, toz kırmızı biber ve kekik': ['cumin', 'paprika', 'oregano'],
    'Toz kırmızı biber ve kuru nane': ['paprika', 'mint'],
    'Deniz tuzu': ['salt'],

    # ── su ────────────────────────────────────────────────────────────
    'Su': ['water'],
    'Sıcak su': ['water'],
    'Ilık su': ['water'],
    'Kaynar su': ['water'],
    'Soğuk su': ['water'],
    'Haşlama suyu': ['water'],
    'Pirinç için su': ['water'],
    'Pilav için sıcak su': ['water'],
    'Fasulye için sıcak su': ['water'],
    'Ayrılmış makarna suyu': ['water'],
    'Az tuzlu sebze suyu veya su': ['water'],
    'Az tuzlu et suyu veya sıcak su': ['water'],
    'Sıcak su veya az tuzlu tavuk suyu': ['water'],
    'Soğuk su veya nohut haşlama suyu': ['water'],

    # ── tahıl / ekmek ─────────────────────────────────────────────────
    'Yulaf ezmesi': ['oats'],
    'Buğday unu': ['flour'],
    'Tam tahıllı ekmek': ['bread'],
    'Tam tahıllı veya rustik ekmek': ['bread'],
    'Bayat ekmek içi': ['bread'],
    'Simit': ['simit'],
    'Lavaş': ['tortilla_wrap'],
    'Buğday tortilla': ['tortilla_wrap'],
    'Un tortillası': ['tortilla_wrap'],
    'Küçük mısır tortillası': ['tortilla_wrap'],
    'Kuru penne': ['pasta'],
    'Kuru küçük makarna': ['pasta'],
    'Kuru buğday noodle': ['noodle'],
    'Kuru pirinç noodle': ['noodle'],
    'Kuru inci arpa': ['barley'],
    'Kuru karabuğday tanesi': ['buckwheat'],
    'Kuru Arborio pirinci': ['white_rice'],
    'Soğuk pişmiş pirinç': ['white_rice'],
    'Kuru pilavlık bulgur': ['bulgur'],
    'Kuru iri pilavlık bulgur': ['bulgur'],
    'Kuru ince köftelik bulgur': ['bulgur'],
    'Kuru ince Kuzey Afrika kuskusu': ['couscous'],
    'Granola': ['granola'],
    'Sade pirinç patlağı': ['rice_cake'],
    'Patlamamış mısır tanesi': ['popcorn'],
    'Mısır tortilla cipsi': ['tortilla_chips'],
    'Sade kurabiye': ['cookies'],

    # ── protein ───────────────────────────────────────────────────────
    'Az yağlı çiğ dana kıyma': ['ground_beef'],
    'Çiğ az yağlı dana kıyma': ['ground_beef'],
    'Az yağlı dana kıyma': ['ground_beef'],
    'Çiğ hindi kıyma': ['ground_turkey'],
    'Çiğ yağsız dana kuşbaşı': ['veal'],
    'Çiğ yağsız dana yahni eti': ['veal'],
    'Çiğ kuzu kuşbaşı': ['lamb'],
    'Çiğ dana ciğeri': ['liver'],
    'Çiğ kemiksiz domuz loin pirzola': ['pork_chop'],
    'Çiğ, derisiz-kemiksiz tavuk but': ['chicken_thigh'],
    'Çiğ kemiksiz, derili tavuk but': ['chicken_thigh'],
    'Çiğ somon fileto': ['salmon'],
    'Füme somon': ['salmon'],
    'Çiğ morina fileto': ['cod'],
    'Çiğ levrek fileto': ['sea_bass'],
    'Suda konserve ton balığı, süzülmüş': ['tuna'],
    'Zeytinyağında konserve sardalya, süzülmüş': ['sardine'],
    'Çiğ, ayıklanmış karides': ['shrimp'],
    'Çiğ ayıklanmış karides': ['shrimp'],
    'Çırpılmış yumurta': ['eggs'],
    'Sert tofu': ['tofu'],
    'Sert tofu, süzülüp bastırılmış': ['tofu'],

    # ── süt ürünleri ──────────────────────────────────────────────────
    'Türk beyaz peyniri': ['feta_cheese'],
    'Yunan feta peyniri': ['feta_cheese'],
    'Labne peyniri': ['labne'],
    'Hafif yemek kreması': ['cream'],
    'Pecorino Romano': ['pecorino'],

    # ── bakliyat ──────────────────────────────────────────────────────
    'Pişmiş, süzülmüş nohut': ['chickpea'],
    'Haşlanmış ve süzülmüş nohut': ['chickpea'],
    'Haşlanmış nohut, süzülmüş': ['chickpea'],
    'Haşlanmış kuru fasulye, süzülmüş': ['white_bean'],
    'Haşlanmış siyah fasulye': ['black_bean'],
    'Haşlanmış siyah fasulye, süzülmüş': ['black_bean'],
    'Haşlanmış ve süzülmüş siyah fasulye': ['black_bean'],
    'Haşlanmış barbunya, süzülmüş': ['kidney_bean'],
    'Haşlanmış ve süzülmüş barbunya': ['kidney_bean'],
    'Pişmiş, süzülmüş yeşil mercimek': ['green_lentil'],
    'Kuru iç bakla, kırık': ['fava_bean'],
    'Dondurulmuş kabuklu edamame': ['edamame'],

    # ── sebze / meyve ─────────────────────────────────────────────────
    'Kırmızı dolmalık biber': ['bell_pepper'],
    'Orta boy dolmalık biber': ['bell_pepper'],
    'Yeşil biber': ['bell_pepper'],
    'Sivri yeşil biber': ['bell_pepper'],
    'Kırmızı biber': ['bell_pepper'],
    'Jalapeño veya serrano biber': ['hot_pepper'],
    'Kurutulmuş ancho biber': ['hot_pepper'],
    'Kereviz sapı': ['celery'],
    'Orta boy patlıcan': ['eggplant'],
    'Olgun domates': ['tomato'],
    'Çeri domates': ['tomato'],
    'Doğranmış konserve domates': ['tomato'],
    'Domates veya biber salçası': ['tomato_paste'],
    'Beyaz soğan': ['onion'],
    'Uzun salatalık': ['cucumber'],
    'Semizotu, ayıklanmış': ['purslane'],
    'Sapları ayıklanmış karalahana': ['kale'],
    'Karalahana (kale), sert sapları alınmış': ['kale'],
    'Salamura asma yaprağı, süzülmüş': ['grape_leaves'],
    'Süzülmüş mısır': ['corn'],
    'Mısır, süzülmüş': ['corn'],
    'Avokado, yenebilir kısım': ['avocado'],
    'Olgun muz': ['banana'],
    'Dondurulmuş mango': ['mango'],
    'Çekirdeksiz hurma': ['dates'],
    'Kuru kayısı': ['dried_apricot'],
    'Kuru üzüm': ['raisins'],
    'Nar tanesi': ['pomegranate'],
    'Zeytin, çekirdeksiz': ['olives'],
    'Limon suyu': ['lemon'],
    'İnce rendelenmiş limon kabuğu': ['lemon'],
    'Misket limonu suyu': ['lime'],

    # ── yağ / sos / baharat / diğer ───────────────────────────────────
    'Nötr sıvı yağ': ['sunflower_oil'],
    'Şekersiz fıstık ezmesi': ['peanut_butter'],
    'Vanilya özütü': ['vanilla'],
    'Öğütülmüş keten tohumu': ['flax_seeds'],
    'Kabak çekirdeği içi': ['pumpkin_seeds'],
    'İç kabak çekirdeği': ['pumpkin_seeds'],
    'Tuzsuz Antep fıstığı içi': ['pistachio'],
    'Şekersiz kakao': ['cocoa_powder'],
    'Tatlı toz biber': ['paprika'],
    'Tatlı veya acı toz biber': ['paprika'],
    'Dijon hardalı': ['mustard'],
    'Beyaz şarap sirkesi': ['white_vinegar'],
    'Düşük sodyumlu soya sosu': ['soy_sauce'],
    'Beyaz miso': ['miso_paste'],
    'Şekersiz rendelenmiş hindistancevizi': ['coconut_flakes'],
    'Şekersiz Hindistan cevizi suyu': ['coconut_water'],
    'Şekersiz hindistancevizi içeceği': ['coconut_water'],
    'Vanilyalı dondurma': ['ice_cream'],
}
